### PR TITLE
Update unsafe_process_primitives to build with gcc/gnat version 10.2.0

### PR DESCRIPTION
**Pull request by charlie5**
In the 'fork' function replace 
    NT_Sec_Stack_Addr : constant System.Address :=  SSL.Get_Sec_Stack_Addr.all;
with
    NT_Sec_Stack : constant SST.SS_Stack_Ptr := SSL.Get_Sec_Stack.all;

### CODE REVIEW

**Comment by Blady-Com** [comment]
Hello Charlie, this has been already fixed in dev branches.
See the last [one](https://github.com/Blady-Com/florist/tree/xnadalib-2019).

**Comment by charlie5** [comment]
Hello, *thank* you for maintaining florist. I use it in several projects.
I've just tried to build the xnadalib-2019 branch on Archlinux (gcc version
10.2.0) and hit a few problems.

Here is the build output ...

   [Ada]          posix-signals.adb
posix-signals.adb:152:43: warning: value not in range of type "Signal"
defined at posix-signals.ads:56
posix-signals.adb:152:43: warning: "Constraint_Error" will be raised at run
time
posix-signals.adb:153:43: warning: value not in range of type "Signal"
defined at posix-signals.ads:56
posix-signals.adb:153:43: warning: "Constraint_Error" will be raised at run
time
posix-signals.adb:201:12: error: dynamic or empty choice in aggregate must
be the only choice
posix-signals.adb:1148:12: error: choice given in case statement is not
static
posix-signals.adb:1148:12: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1148:22: error: choice given in case statement is not
static
posix-signals.adb:1148:22: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1148:31: error: choice given in case statement is not
static
posix-signals.adb:1148:31: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1148:40: error: choice given in case statement is not
static
posix-signals.adb:1148:40: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1148:50: error: choice given in case statement is not
static
posix-signals.adb:1148:50: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1148:59: error: choice given in case statement is not
static
posix-signals.adb:1148:59: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1150:12: error: choice given in case statement is not
static
posix-signals.adb:1150:12: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.adb:1150:22: error: choice given in case statement is not
static
posix-signals.adb:1150:22: error: expression raises exception, cannot be
static (RM 4.9(34))
posix-signals.ads:67:52: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:67:52: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:69:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:69:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:71:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:71:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:73:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:73:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:75:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:75:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:77:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:77:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:79:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:79:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:81:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:81:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:83:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:83:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:85:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:85:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:87:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:87:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:89:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:89:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:91:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:91:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:93:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:93:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:95:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:95:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:100:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:100:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:102:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:102:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:104:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:104:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:106:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:106:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:108:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:108:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:110:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:110:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:115:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:115:59: warning: "Constraint_Error" will be raised at run
time
posix-signals.ads:117:59: warning: value not in range of type "Signal"
defined at line 56
posix-signals.ads:117:59: warning: "Constraint_Error" will be raised at run
time
gprbuild: *** compilation phase failed
make: *** [Makefile:156: floristlib] Error 4
==> ERROR: A failure occurred in build().
    Aborting...


Any hints on what I may have done wrong ?

Regards.

**Comment by Blady-Com** [comment]
Hello, all errors and warnings seem to come from a wrong detected number of signals.
In the generated posix-c.ads, I got on my side:
   NSIGS : constant := 32;
What had you got on your side?
The file is generated by c-posix.c, see by lines 5200.
Had you got logs when executing c-posix?

**Comment by charlie5** [comment]
Hi again, please pardon the delay in replying. Did not have a chance to
look into this yesterday.

   NSIGS : constant := -1;

Attached are the logs.

Regards.

**Comment by charlie5** [comment]
In case it helps, I didn't see this problem when I used the 'master' branch.

**Comment by Blady-Com** [comment]
I can't find the logs.
Well, the relevant change I've found is [there](https://github.com/Blady-Com/florist/commit/abe444e4923c0c0aa3e453c6cd14d849a8987abb#diff-af562b9d1df212d056cb787a67704c2d).
But I don't see why it worked before.
What is the return values of sigismember for your system? (man sigismember)
After the call of sigismember line 5208, could you print the result value?

**Comment by charlie5** [comment]
sigismember() returns 1 if signum is a member of set, 0 if signum is not a
member, and -1 on error.

Attached is the c-posix log with the result values shown.

**Comment by Blady-Com** [comment]
I can't find any attached files.
Can you please send them to blady dot com at wanadoo dot fr?

**Comment by Blady-Com** [comment]
A fix has been pushed in [master](https://github.com/Blady-Com/florist/commit/8eb622bce2181af56f7acca94cbf2acd10c19917) branch.
Is it correct for you ?

**Comment by charlie5** [comment]
I now get this error ...

posix-sockets-iso.ads:284:26: error: value not in range of type "u_char"
defined at line 262
posix-sockets-iso.ads:284:26: error: static expression fails
Constraint_Check

c-posix.c:#ifdef AF_ISO
c-posix.c:  GCST("AF_ISO", AF_ISO);
c-posix.c:  GDFLT("AF_ISO", 0);
c-posix.log:missing: AF_ISO

gensrc/posix-c.ads:      --  *** MISSING: AF_ISO ***  --
gensrc/posix-c.ads:      AF_ISO : constant := 99012;

**Comment by Blady-Com** [comment]
Good catch, I had made a quick hack to avoid case duplication values in tests but I hadn't seen potential side effects :-(
I revert the changes in [last commit](https://github.com/Blady-Com/florist/commit/515029535b29b23a3da9761c7e2e52948ea458ea) and add a dedicated macro for those non supported values which need a uniq value.
Is it better now?

**Comment by Blady-Com** [comment]
Last [commit](https://github.com/Blady-Com/florist/commit/515029535b29b23a3da9761c7e2e52948ea458ea) has fixed the issue.

**Pull request closed without merging**
