### PR TITLE
Remove unnecessary 'with' of ancestors.

### PR DESCRIPTION
**Pull request by charlie5**
These warnings cause building, with warnings treated as errors, to fail.

The new warnings were introduced in GCC 12.

Would it be possible to also update alire's 'florist_blady' ?

Regards.

### CODE REVIEW

**Comment by Blady-Com** [comment]
There are other warnings.
You can catch them with command: `% make ADAFLAGS=-gnatwn`
Thus you might complete the changes.
PS: What is your environnement?
Thanks, Pascal.

**Comment by charlie5** [comment]
I'll take a look and *try* to fix the other warnings.

I'm on Archlinux.

**Comment by charlie5** [comment]
I've fixed the 'possible aliasing problem' warnings according to the advice given here ... https://gcc.gnu.org/onlinedocs/gnat_ugn/Optimization-and-Strict-Aliasing.html .

I've used the No_strict_Aliasing pragma, for the problematic access types, since it ensures no problem will occur, rather than relying on the optimisation level and/or compiler switches.

Please let me know if you have any reservations or feedback re the changes.

There remains several warnings regarding 'size is not a multiple of alignment'. I'll try to take a look at those asap.

**Comment by Blady-Com** [comment]
Hello, tell me if you'll have more commit to add.
If not I'll merge them.
But before could you please revert commit for [-gnatwn](https://github.com/Blady-Com/florist/pull/6/commits/1d659bf2d8916be1b3392ae3735433ccab1ac558) because additional options like this can be set with [ADAFLAGS](https://github.com/Blady-Com/florist/blob/master/florist.gpr#L51) environment variable ?

**Comment by charlie5** [comment]
Hi Pascal,

   I have no more commits at the moment.
   I've reverted the '-gnatwn' commit.


   I just noticed in the README that you say ...

   alr with florist

Should that be ...

   alr with florist_blady

... ?


Thanks for accepting the PR :) .

**Comment by Blady-Com** [comment]
Thanks for reporting Pascal.

**Pull request merged**
